### ISSUE TITLE
New Instance After Sleep Clears the HT16K33 Display

### ISSUE THREAD

**Issue by ThisIsMyGitHubUserName01** [electricimp/HT16K33Segment#3]
Currently I have an Imp controlling an HT16K33. When the imp goes to sleep on idle, I wake after a second or so, and need to make a "new" instance of the HT16K33 class def, since I loose everything not in nv table. When I make a new instance, the display goes blank briefly. This is very undesirable. I want the display to keep the last value until the new value is written to the display. 

Also, I saw the class definition for the HT16K33 display clears the display (init() is called on line 61) when you make a new instance, so instead of #require "HT16K33Segment.class.nut:1.0.1", I just copied the whole class definition manually into my device code and commented out the init() in the constructor. I thought I really had it there, but alas, the display still clears itself when I make a new instance each time the imp wakes. I also kept the old value in nv table, and right after making a new instance of HT16K33 wrote the old value, still, the display goes blank for maybe 0.1 seconds when the new instance is made.

The display also seems to, I don't know, "sizzle" in intensity. I imagine most folks wouldn't notice, but it does not do this if the Imp is prevented from going to sleep. Display brightness is set to the lowest value. 

I either need a way to save an instance of a class when the imp goes to sleep, or a way to start a new instance of the HT16K33 that will not clear the display.

Thanks for any help!

**Comment by smittytone** [comment]
Interesting question. I'm not sure of the answer right now as all of my various devices that make use of this class do not sleep because the display is updated continually (temperature, time, etc).

If you have removed _init()_ from your device code, you should check that some other part of your application isn't calling _setBrightness()_, as this currently causes the display to power-cycle, which is done because manually power-cycling the display sets it to power off mode until you send it the signal to turn the LEDs on. The class does this automatically in _setBrightness()_ so that all you need do to get the display up is instantiate the class (constructor calls _init()_, _init()_ calls _setBrightness()_).

You can edit the class to remove this behavior, but you risk not having the display visible after a manual power-cycle. All this is a product of the HT16K33 controller.

Best thing then is to add back _init()_ but comment out the _clearDisplay()_ call.

**Comment by ThisIsMyGitHubUserName01** [comment]
I was calling setBrightness() also. Removing that (and previously removing the init() in the constructor.) seems to have worked, and the display remains on! Thanks for the help.

The display still seems to sizzle in intensity, but it is very minor and may be related to the imp going from sleep state to awake, and the load may differ enough to cause the display brightness to sizzle.
